# Generated by Django 3.1.3 on 2020-12-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handworker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateworkers',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workers',
            name='is_aviable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_base',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='ar_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_base',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='workers',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workers',
            name='total_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
